apiVersion: v1
kind: List
metadata:
  name: k8s-monitoring
items:

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: prometheus
      labels:
        app: k8s-monitoring
    data:
      prometheus.yml: |-
        global:
          scrape_interval:     60s # By default, scrape targets every 15 seconds.
          evaluation_interval: 30s

          # Attach these labels to any time series or alerts when communicating with
          # external systems (federation, remote storage, Alertmanager).
          external_labels:
            monitor: 'reachlin'
        rule_files:
          - "/etc/prometheus/*.rules"
        # A scrape configuration containing exactly one endpoint to scrape:
        # Here it's Prometheus itself.
        scrape_configs:
          - job_name: 'blackbox'
            metrics_path: /probe
            params:
              module: [http_2xx]  # Look for a HTTP 200 response.
            static_configs:
              - targets:
                - https://reachlin.github.io
                - http://127.0.0.1:8888
            relabel_configs:
              - source_labels: [__address__]
                target_label: __param_target
              - source_labels: [__param_target]
                target_label: instance
              - target_label: __address__
                replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
      alert.rules: |-
        ALERT BlackboxServiceDown
          IF probe_success == 0
          FOR 1m
          LABELS { severity = "critical" }
          ANNOTATIONS {
            summary = "Instance {{ $labels.instance }} down",
            description = "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes.",
          }
      alertmanager.yml: |-
        global:
          resolve_timeout: 5m
        route:
          group_by: [cluster]
          receiver: default
          routes:
            - match:
                severity: critical
              receiver: default

        receivers:
        - name: default
          pagerduty_configs:
          - service_key: $PD_KEY

      blackbox.yml: |-
        modules:
          http_2xx:
            prober: http
            timeout: 5s
            http:
              method: GET
              no_follow_redirects: false
              preferred_ip_protocol: "ip4"
              fail_if_ssl: false
              fail_if_not_ssl: false

  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
      labels:
        app: k8s-monitoring
      name: k8s-monitoring
    spec:
      selector:
        app: k8s-monitoring
      type: NodePort
      ports:
      - name: prometheus
        protocol: TCP
        port: 9090
        nodePort: 30090
      - name: blackbox
        protocol: TCP
        port: 9115
        nodePort: 30091

  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: k8s-monitoring
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: k8s-monitoring
      template:
        metadata:
          name: k8s-monitoring
          labels:
            app: k8s-monitoring
        spec:
          containers:
          - name: prometheus
            image: quay.io/coreos/prometheus:latest
            args:
              - '-config.file=/etc/prometheus/prometheus.yml'
              - '-alertmanager.url=http://localhost:9093'
            ports:
            - name: prometheus
              containerPort: 9090
            volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
          - name: blackbox
            image: prom/blackbox-exporter:latest
            args:
              - '--config.file=/etc/blackbox/blackbox.yml'
            ports:
            - name: blackbox
              containerPort: 9115
            volumeMounts:
            - name: config-volume
              mountPath: /etc/blackbox
          - name: alertmanager
            image: prom/alertmanager:latest
            args:
              - '--config.file=/etc/alertmanager/alertmanager.yml'
            ports:
            - name: alertmanager
              containerPort: 9093
            volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager
          volumes:
          - name: config-volume
            configMap:
              name: prometheus
